// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK7Kw2FEZlUAh5GPWeWUse_BzYbHeD9Lw',
    appId: '1:622563610415:web:b7db996d031307a09edbda',
    messagingSenderId: '622563610415',
    projectId: 'habit-tracker-2e379',
    authDomain: 'habit-tracker-2e379.firebaseapp.com',
    storageBucket: 'habit-tracker-2e379.firebasestorage.app',
    measurementId: 'G-CTVZY9DEEY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0wAzALXglbi2vFlN1npuKbLLAW52m9H0',
    appId: '1:622563610415:android:bf3ec79d01ba1b309edbda',
    messagingSenderId: '622563610415',
    projectId: 'habit-tracker-2e379',
    storageBucket: 'habit-tracker-2e379.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOb2MJAc1MGhLVHXx_hNeWw7bmK2H1MnY',
    appId: '1:622563610415:ios:c809a337ddc881e29edbda',
    messagingSenderId: '622563610415',
    projectId: 'habit-tracker-2e379',
    storageBucket: 'habit-tracker-2e379.firebasestorage.app',
    iosBundleId: 'com.habeats',
  );
}
